CREATE TABLE ETUDIANT (
IDENTIFIANT INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(256),
PRENOM VARCHAR (256),
MATRICULE INT,
SEXE VARCHAR (2),
NIVEAU INT,
FILIERE VARCHAR (10),
PRIMARY KEY (IDENTIFIANT)
);